# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- #1134

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    wget https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
    pwd
    ls -lRt
  displayName: 'Download jdk'
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '16'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: 'OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz'
    jdkDestinationDirectory: '/opt/jdkcustom'
    cleanDestinationDirectory: true
- script: |
    java -version
    ls -lRt
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '/opt/jdkcustom/JAVA_HOME_16_X64_OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7_tar.gz/jdk-16.0.2+7'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
